USE [master]
GO
/****** Object:  Database [BugTracker]    Script Date: 16-02-2023 11:09:23 ******/
CREATE DATABASE [BugTracker]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BugTracker', FILENAME = N'C:\Users\vivek\BugTracker.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BugTracker_log', FILENAME = N'C:\Users\vivek\BugTracker_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BugTracker] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BugTracker].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BugTracker] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BugTracker] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BugTracker] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BugTracker] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BugTracker] SET ARITHABORT OFF 
GO
ALTER DATABASE [BugTracker] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BugTracker] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BugTracker] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BugTracker] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BugTracker] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BugTracker] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BugTracker] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BugTracker] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BugTracker] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BugTracker] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BugTracker] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BugTracker] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BugTracker] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BugTracker] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BugTracker] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BugTracker] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BugTracker] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BugTracker] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BugTracker] SET  MULTI_USER 
GO
ALTER DATABASE [BugTracker] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BugTracker] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BugTracker] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BugTracker] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BugTracker] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BugTracker] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BugTracker] SET QUERY_STORE = OFF
GO
USE [BugTracker]
GO
/****** Object:  Table [dbo].[AppRole]    Script Date: 16-02-2023 11:09:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AppRole](
	[RoleId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_AppRole] PRIMARY KEY CLUSTERED 
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AppUser]    Script Date: 16-02-2023 11:09:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AppUser](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](200) NOT NULL,
	[FullName] [nvarchar](200) NOT NULL,
	[AvatarUrl] [nvarchar](200) NULL,
	[PasswordHash] [varbinary](max) NOT NULL,
	[PasswordSalt] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_AppUser] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Bug]    Script Date: 16-02-2023 11:09:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bug](
	[BugId] [int] IDENTITY(1,1) NOT NULL,
	[SoftwareProjectId] [int] NOT NULL,
	[ReportedOn] [datetime2](7) NOT NULL,
	[Description] [nvarchar](500) NOT NULL,
	[ResolutionStatus] [int] NOT NULL,
 CONSTRAINT [PK_Bug] PRIMARY KEY CLUSTERED 
(
	[BugId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Message]    Script Date: 16-02-2023 11:09:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Message](
	[MessageId] [int] IDENTITY(1,1) NOT NULL,
	[BugId] [int] NOT NULL,
	[CreatedOn] [datetime2](7) NOT NULL,
	[MessageDescription] [nvarchar](500) NOT NULL,
	[IsResolved] [bit] NOT NULL,
 CONSTRAINT [PK_Message] PRIMARY KEY CLUSTERED 
(
	[MessageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SoftwareProject]    Script Date: 16-02-2023 11:09:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SoftwareProject](
	[SoftwareProjectId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](200) NULL,
	[CreatedOn] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_SoftwareProject] PRIMARY KEY CLUSTERED 
(
	[SoftwareProjectId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserRole]    Script Date: 16-02-2023 11:09:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRole](
	[UserId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
 CONSTRAINT [PK_UserRole] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Message] ADD  CONSTRAINT [DF_Message_IsResolved]  DEFAULT ((0)) FOR [IsResolved]
GO
ALTER TABLE [dbo].[Bug]  WITH CHECK ADD  CONSTRAINT [FK_Bug_SoftwareProject] FOREIGN KEY([SoftwareProjectId])
REFERENCES [dbo].[SoftwareProject] ([SoftwareProjectId])
GO
ALTER TABLE [dbo].[Bug] CHECK CONSTRAINT [FK_Bug_SoftwareProject]
GO
ALTER TABLE [dbo].[Message]  WITH CHECK ADD  CONSTRAINT [FK_Message_Bug] FOREIGN KEY([BugId])
REFERENCES [dbo].[Bug] ([BugId])
GO
ALTER TABLE [dbo].[Message] CHECK CONSTRAINT [FK_Message_Bug]
GO
ALTER TABLE [dbo].[UserRole]  WITH CHECK ADD  CONSTRAINT [FK_UserRole_AppRole] FOREIGN KEY([RoleId])
REFERENCES [dbo].[AppRole] ([RoleId])
GO
ALTER TABLE [dbo].[UserRole] CHECK CONSTRAINT [FK_UserRole_AppRole]
GO
ALTER TABLE [dbo].[UserRole]  WITH CHECK ADD  CONSTRAINT [FK_UserRole_AppUser] FOREIGN KEY([UserId])
REFERENCES [dbo].[AppUser] ([UserId])
GO
ALTER TABLE [dbo].[UserRole] CHECK CONSTRAINT [FK_UserRole_AppUser]
GO
USE [master]
GO
ALTER DATABASE [BugTracker] SET  READ_WRITE 
GO
